export * from "./financial-engine.types.js";
export * from "./financial-engine.errors.js";
export { assertValidHypotheses } from "./financial-engine.validation.js";
export { computeResult, computeBreakEven, type BreakEvenInput } from "./financial-engine.calculations.js";
export { applyDelta, applyScenario, SCENARIO_DELTAS, type ScenarioKey, type SensitivityDelta } from "./scenarios.js";
export { computeAnnualProjection, SEASONALITY_PROFILES, type SeasonalityProfileKey, type MonthlyResult } from "./seasonality.js";
export { computeCapitalNeed, CASH_RESERVE_MONTHS, type CapitalPlanInput, type CapitalNeed } from "./capital.js";
export { computeSensitivity, SENSITIVITY_PERCENT, type SensitivityKey, type SensitivityEntry } from "./sensitivity.js";
export { computeWatchPoints, THIN_MARGIN_PERCENT, type WatchPointCode } from "./watch-points.js";
export { approxEurFromXof, fromMinorUnits, minorUnitDigits, relabelCurrency, toMinorUnits, XOF_PER_EUR } from "./money.js";
